"""empty message

Revision ID: f9057f2a92ec
Revises: 
Create Date: 2026-05-29 10:18:17.573877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9057f2a92ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('groupname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('groupname'),
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product', sa.String(length=150), nullable=False),
    sa.Column('product_code', sa.String(length=150), nullable=False),
    sa.Column('product_category', sa.String(length=150), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code'),
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username'),
    mysql_engine='InnoDB'
    )
    op.create_table('group_members',
    sa.Column('group_member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_member_id'),
    sa.UniqueConstraint('group_id', 'user_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inout_date', sa.DateTime(), nullable=False),
    sa.Column('stock_type', sa.String(length=150), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('stock_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('task_content', sa.String(length=3000), nullable=True),
    sa.Column('task_status', sa.Enum('unstarted', 'progress', 'complete'), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('task_comment', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('alert_type', sa.Enum('registered', 'updated', 'comment_added', 'deadline', 'group_deleted'), nullable=False),
    sa.Column('alert_since', sa.DateTime(), nullable=True),
    sa.Column('alert_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('alert_users',
    sa.Column('alert_user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_user_id'),
    sa.UniqueConstraint('alert_id', 'user_id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_users')
    op.drop_table('alerts')
    op.drop_table('tasks')
    op.drop_table('stocks')
    op.drop_table('group_members')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('groups')
    # ### end Alembic commands ###
